### ISSUE TITLE
사람이 직접 하는 것 처럼 속여봅시다

### ISSUE THREAD

**Issue by notjoshlee** [Caffeinism/ssakdduk#1]
Selenium이나 PhantomJS 사용해서 사람이 직접 하는 것 처럼 속여봅시다.

부매니저 아이디 3개 사용해서 3교대로 사람이 직접 관리한다고 합시다.

글 하나 읽을 때 마다 `글 길이`에 비례해서 딜레이 줍시다.

**Comment by Caffeinism** [comment]
사실 지금보다 부하 훨신 줄게 그냥 코멘트 읽는거에 텀을 주면 충분히 사람이 관리하는 속도보다 아주 조금 빠르게 자동관리하는 식으로 할 수 있는데, 아무래도 그냥 사용하는거 자체를 싫어하는 것 같더라고요.

**Comment by Caffeinism** [comment]
막는것도 이미 한두번이 아니고.. 그냥 싹둑이 사용을 안하는걸 원하는 것 같아요. 통피/외국 아이피 사용 못하게 하는 기능이 추가되지 않는 한 그냥 이런대로 써야하나봐요.
